#!/usr/bin/env bash
# Install nginx on my web01 server
# Configure nginx server to have a custom 404 page that contains
# "Ceci n'est pas une page"
sudo apt-get -y install nginx
sudo service nginx start
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/error_404.html
sudo sed -i "44i\error_page 404 /404.html;\nlocation = /404.html {\n\tinternal;\n\treturn 404 \"Ceci n'est pas une page\";\n}" /etc/nginx/sites-available/default
sudo service nginx restart
