#!/usr/bin/env bash
# Script that configures a new Ubuntu machine to requirements

sudo apt-get update
sudo apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html
echo "Ceci n'est pas une page" \
  | sudo tee /usr/share/nginx/html/404.html
sudo sed -i "s/server_name _;/server_name _;\n\
\trewrite ^\
\/redirect_me https:\/\/github.com\/kuuqua permanent;\n\
\n\
\terror_page 404 \/404.html;\n\
\tlocation = \/404.html {\n\
\t\troot \/usr\/share\/nginx\/html;\n\
\t\tinternal;\n\
\t}/" /etc/nginx/sites-available/default
sudo service nginx restart
